### ISSUE TITLE
Faire les tests pour une des routes du back

### ISSUE THREAD

**Issue by socarboni** [heartnotation/heartnotation#100]
Choisir entre #8, #38, #12, #13, #56, #71, #63, #68, #69, #72, #140, #105 et #19 
Une fois fait, créer des issues pour lancer les tests des autres

**Comment by romph** [comment]
- [x] Template des tests unitaires pour la vérification de la méthode, du routage, du payload et des codes renvoyés.
- [x] Template des tests REST (via requête) pour la méthode GET
- [ ] Template des tests REST (via requête) pour les méthodes PUT, POST, DELETE

**Comment by socarboni** [comment]
Les tests du back tests des choses actuellement non en place.
Les  corrections necessaires vont être mis en place pour la verification de la méthod d'appel, ainsi que du path d'appel.
Les tests concernant le format de l'objet envoyé vont être mis de coté pour le moment pour pouvoir prévoir la release. Un autre issue va être ouvert pour mettre en place les protection necessaire pour faire fonctionner ces tests là.

**Comment by socarboni** [comment]
Ne sera surement pas fait, donc closed
