### ISSUE TITLE
Ecran d'administration d'organisations

### ISSUE THREAD

**Issue by MarvinLeclerc** [heartnotation/heartnotation#166]
issues référence : 
- #120
- #115

**Comment by MarvinLeclerc** [comment]
**Attention à la casse !!!!!!!!!!!!!!**

**Comment by tholander** [comment]
Flemme de faire à la volée, ça va foutre la merde. Du coup, on rajoute une vraie interface d'amin

**Comment by tholander** [comment]
PR #254

**Comment by socarboni** [comment]
Fini, donc je close
