### ISSUE TITLE
[FIX] Page annotation

### ISSUE THREAD

**Issue by rolextaing** [heartnotation/heartnotation#189]
- Bouton interval qui devient inutile, à retirer.
- bouton do/redo, voir si on les fait ou pas.
- Mettre le toggle de zoom/posage d'interval dans à coté de display leads

**Comment by tholander** [comment]
PR en cours #210

**Comment by socarboni** [comment]
Leger fix qui reste: supprimer l'affichage des etiquette "magenta, cyan, ..." de la page d'annotation. Fix fait sur la branch 138 car trop leger pour valoir une branch complete

**Comment by socarboni** [comment]
Demo faite, je close
