### ISSUE TITLE
Traiter annotation : changement de statut

### ISSUE THREAD

**Issue by socarboni** [heartnotation/heartnotation#208]
Il faut pouvoir changer d'état une annotation, dire que son traitement est fini, puis pouvoir la validée ou non.
Normalement, il y a dejà des elements pour ça, mais ils ne sont pas disponibles depuis une annotation (?)
Empecher la modification de l'annotation (interval/tags, mais laisser la possibilité de commenter) en dehors de la phase de traitement (assigné qui devient en cours de traitement a la premiere ouverture de l'annotation par un annotateur assigné, jusqu'a la demande de validation)

**Comment by tholander** [comment]
PR en cours #210

**Comment by socarboni** [comment]
Mergé, je close
