### ISSUE TITLE
[BUG Fix] Problème lors de l'utilisation de librairies Go

### ISSUE THREAD

**Issue by MarvinLeclerc** [heartnotation/heartnotation#30]
## Problème

Grâce au développement de l'issue #8, un problème d'import de librairies est survenu.

## Solution

Pour que les librairies soient utilisables, il vous faudra changer votre $GOPATH avec la commande suivante :

``` bash
export GOPATH=/home/last/Documents/LP/heartnotation/back
``` 

> Vu avec Saïd : pour les librairies, cela fonctionne comme il faut mais le problème est apparu lors du développement sur #8 qui utilise un package créer dans le package main

**Comment by MarvinLeclerc** [comment]
@saidkhalid @apliez @tholander @romph @socarboni 
Si vous avez un problème avec les imports de librairies et de package, venez me voir avant d'appliquer ce fix

**Comment by socarboni** [comment]
C'est une manip que tout le monde doit faire, non ?

**Comment by socarboni** [comment]
Plus valable, attendre correction de @MarvinLeclerc  ou aller le voir directement
Le fix proposé ne suffit pas/marche pas

**Comment by socarboni** [comment]
![20190206_160412](https://user-images.githubusercontent.com/43568913/52351239-9fd46280-2a2a-11e9-843e-2347cfbc1d64.jpg)
Suite du fix

**Comment by MarvinLeclerc** [comment]
> Les messages précédents ne sont plus a considérer

## En cas de problème de GOPATH

Si une erreur parlant des dépendances (comme gorilla/mux) survient, les actions à suivre sont les suivantes :  
- Modifier la ligne à la fin du ficher ~/.bashrc 
``` bash
export GOPATH=$HOME/go
```

en 

``` bash
export GOPATH=$HOME/``Dossier de clonne du repo``/heartnotation/back
```

- lancer la commande ```source ~/.bashrc```
