### ISSUE TITLE
[CRITIQUE] Revoir la BDD

### ISSUE THREAD

**Issue by rolextaing** [heartnotation/heartnotation#36]
Problèmes reperés;
- Probleme de comprehension entre statut/process, clarifier ce que sont les status, idealement, renommer process en statut, et le statut en autre chose, car dans toute la documentation qu'on a, on parle de statut pour ce qui s'apelle process uniquement dans la base de donnée
- Process (dans la sens actuel de la BDD) incomplet, il manque beaucoup de "process" (status dans la doc)
- La date d'edition d'une annotation doit : soit pouvoir etre nulle, soit on s'entend sur le fait qu'a la création d'une annotation, la date de création doit être la date de derniere edition, il faut decider et acter ça.
- ~~Changer les dates pour les passer en timestamp? Il y a des problèmes actuellement pour lire les dates par manque de drivers fonctionnant avec le format actuel~~
- L'organizationId ne peut pas etre nul dans une annotation alors que dans la doc on dit que oui
- Créer une organization avec organizationId "0" et avec nom "" pour les cas de non assignation?

**Comment by socarboni** [comment]
@romph merci de faire tes remarques sur les problèmes de bdd ici :) (ou tes questions)

**Comment by MarvinLeclerc** [comment]
AUTO_INCREMENT pour le ID des tables (clé primaire)

**Comment by romph** [comment]
Pour les dates je pense que c'est au choix (à voir les problématiques du back mais je pense que les deux sont faisables), timestamp c'est simple à gérer en base mais ça oblige à convertir par la suite.

J'ai une petite interrogation sur comment éviter les doublons par exemple : deux organisations avec le même nom (ça doit être fait au niveau de la base de données ou par le back ? Il me semble plus naturel que la base gère ça, auquel cas il faut réfléchir aux problématiques de casse).

👍 Pour les cas de non assignation je trouve ça simple et élégant de créer une entrée dans la base dédiée à ça.

**Comment by tholander** [comment]
Je pense que pour les non assignation il vaut mieux pouvoir mettre l'id et le nom de l'organisation à NULL.
Et pour les dates c'est quoi le problème avec le format ?

**Comment by socarboni** [comment]
Le problème avec le format est en train d'être verifié par Said. Le fait d'avoir une string pose des problèmes de traitement, actuellement, il n'a pas de solution pour recuperer la date en string et l'adapter pour un autre affichage

**Comment by socarboni** [comment]
- Le schéma de la BDD est à vérifié, il y a potentiellement des erreurs
- Les annotations parents ne peuvent pas être null? Pas normal

**Comment by rolextaing** [comment]
Rajouter un champ 'isEditable'
Remplacer les status par 'isActive'
Table Process -> Status
Insert tous les status
Rajouter une organization par defaut pour gérer les organization non null
Lastedit = creation date(a documenter)
Changer les dates en timestamp
-> changer les données tests
mettre à jour le schema
AUTO_INCREMENT pour le ID des tables (clé primaire)

rq: ne pas pouvoir ajouter comme organization 'toto' & 'TotO'
