### ISSUE TITLE
Fix les credential en clair pour connexion à la base

### ISSUE THREAD

**Issue by MarvinLeclerc** [heartnotation/heartnotation#41]
Avec @saidkhalid, nous avons du nous connecter à la base de donnée pour les routes de l'API mais les credentials sont mis en clair dans le code.

**Objectif**
- Utiliser les var d'environnement (OS.env dans golang)
- Modifier les codes existants 
- Documenter les choses à faire pour tous

**Comment by socarboni** [comment]
Plus en clair dans le code, mais toujours en clair dans un fichier

**Comment by socarboni** [comment]
Update @MarvinLeclerc, où ça en est? 
Plus personne n'est assigné dessus, mais le post-it a disparu, et la documentation demandé dans le com original n'existe pas.
Qu'est-ce qu'il reste a faire?

**Comment by socarboni** [comment]
Dans le .env, mais on laisse comme ça. je close
