### ISSUE TITLE
[ DOC ] Structuration du Backend & règles de code

### ISSUE THREAD

**Issue by MarvinLeclerc** [heartnotation/heartnotation#42]

**Comment by socarboni** [comment]
Ne pas oublié de prevoir le package "Utils" notamment pour gérer les codes d'erreurs

**Comment by MarvinLeclerc** [comment]
## Architecture Backend

### Comment est structuré le backend ?

Après la réunion de conception Backend, une structure de Backend en est ressorti : 

![untitled diagram](https://user-images.githubusercontent.com/23117553/52330350-8b29a780-29f5-11e9-8902-cc1ca2199333.png)

Voici les fonctions de chacun des fichiers : 
- main.go : contient le corps du programme
- annotationModel.go : ce fichier contiendra la définition de la structure de l'annotation et les méthodes spécifique à la structure déclaré dans ce fichier
- annotationHandler.go : ce fichier gère les ajout des différentes routes à écouter pour les routes spécifiques aux annotations
- annotationManager.go : ce fichier est l'intermédiaire entre le handler et la base de données, seul lui peut agir sur la base et lancer les actions spécifiques aux routes du handler
- *_test.go : les fichiers ayant ce format sont les fichiers contenant les tests unitaires

> NB : Dans cette liste, le nom *annotationModel* est ici à titre d'indication et d'exemple

Pour bien comprendre la répartitions des responsabilités pour les différents fichiers, nous avons le schéma suivant : 

![untitled diagram 1](https://user-images.githubusercontent.com/23117553/52330694-566a2000-29f6-11e9-8370-74a1d31af194.png)


### Les idées restantes en suspend 

Le schéma d'architecture ci-dessus est la décision final de la réunion qui as eu lieu le 5/02/19 mais toute l'équipe doit rester ouverte aux modifications et remonter les problèmes rencontrés durant le développement du Backend.

Les pistes restantes ouvertes sont les suivantes : 
- mettre les déclarations de routes dans un Handler.go présent dans le package 
- création d'un router (``mux.router``) par package pour avoir des routers spécialisés

**Comment by socarboni** [comment]
Ok pour moi. 
Seul point qui me manque, je pense que donner un package d'exemple (genre, dire celui annotation si il respecte bien la structure et a déjà un peu de contenu), pour dire de jeter un oeil dessus, je pense que c'est un +.

**Comment by socarboni** [comment]
![image](https://user-images.githubusercontent.com/43568913/52335245-30e31380-2a02-11e9-904e-a786c3ac5e2b.png)
On aurait pas oublié ça par hasard? D'ailleurs, les erreurs qu'on voulait mettre dans un package "util", on devrait pas les mettre là dedans plutot?

**Comment by socarboni** [comment]
Pour tracer ce qu'on a dit a l'oral : Oui, il faut mettre la gestion des erreur dans commun, quand on fera la gestion des erreurs, pour l'instant on reste avec la gestion d'erreur de base de go.

**Comment by romph** [comment]
UPDATE : dots - manager - models
