### ISSUE TITLE
Rendre le formulaire utilisable

### ISSUE THREAD

**Issue by socarboni** [heartnotation/heartnotation#5]
Le formulaire doit être rendu fonctionnel, sauf, la verification du signal.
Taches précédentes ;
- #4

**Comment by MarvinLeclerc** [comment]
{
"idAnnotation": 17,
"idAnnotationParent": 16, (OPTIONNAL)
"organizationID": 1000,
"idSignal": 1,
"annotationComment": "test pour insert"
}

Format nécessaire au BACK pour l'insertion en base (si ajout d'informations, prevenir le BACK)

**Comment by MarvinLeclerc** [comment]
@tholander vu que tu aura modifier la structure après le Gorm, regarde si ça correspond toujours

**Comment by romph** [comment]
Update du format JSON :
{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"title" : "Titre de l'annotation"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"signal_id" : 3
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"organization_id" : 2
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_"annotation_parent_id": 16_,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_"organization_id": 1000_,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"authorized_tags": [1, 2, 12]
}
Les lignes en italique signifient qu'elles sont optionnelles.
