### ISSUE TITLE
Réunion conception back

### ISSUE THREAD

**Issue by socarboni** [heartnotation/heartnotation#7]
Concevoir la structure du back end

**Comment by MarvinLeclerc** [comment]
Points relevés lors de la réflexion/réunion  : 

- Besoin d'un handler au niveau du Main.go ?
- Doit-on "activer" tous les handlers de package pour qu'ils écoutent le handler global ?
- Handler global "complexe" dû  aux différentes requêtes possibles
- Organisation du CDCT a revoir (Router des packages amené à disparaitre)
