### ISSUE TITLE
Gérer la connexion d'un utilisateur

### ISSUE THREAD

**Issue by socarboni** [heartnotation/heartnotation#79]
Tache anterieur ;
- #80 

Gérer les dashboard selon l'utilisateur connecté
Voir si il faudrait pas avoir un onglet "liste des utilisateurs" plutôt que dashboard pour l'administrateur, dans l’hypothèse ou on a un admin qui cumule d'autres rôles

**Comment by socarboni** [comment]
Redecouper en plusieurs issues si trop gros/complexe

**Comment by apliez** [comment]
@socarboni @MarvinLeclerc @tholander Pourquoi un admin peut cumuler des rôles alors qu'il a tous les droits ?

**Comment by tholander** [comment]
Bah en soit ça sert à rien pour un admin qu'il cumul des rôles je pense, mais pour les autres ça pourrait servir donc autant ne pas faire d'exception, on se fera moins chier je pense

**Comment by socarboni** [comment]
Je réouvre, les boutons de traitement d'annotation n'ont pas l'air d'avoir été correctement traité. A voir aussi pour la pose d'interval.

Concernant la pose de commentaire, a mon avis seul les gestionnaires et annotateur doivent pouvoir le faire (a mon avis, il y a matiere a debattre)

**Comment by MarvinLeclerc** [comment]
Les limitations front sont faites

**En attente du merge de la refonte DB** @rolextaing @apliez prevenez moi quand vous avez fini s'il vous plaît :smile:

**Comment by socarboni** [comment]
Mergé, je close
